server:
  port: 7070

spring:
  profiles: dev
  # 指定当前微服务对外暴露的名称
  application:
    name: demo-consumer-depart

eureka:
  # 指定eureka服务中心
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

# 开启 Feign 对 Hystrix 的支持
feign:
  hystrix:
    enabled: true

---
server:
  port: 9090

spring:
  profiles: test
  # 指定当前微服务对外暴露的名称
  application:
    name: demo-consumer-depart

eureka:
  # 指定eureka服务中心
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka

# 开启 Feign 对 Hystrix 的支持
feign:
  hystrix:
    enabled: true